### PR TITLE
Fix input disabling

### PR DESCRIPTION
**Pull request by scalvert**
Fixes the input disabling where using `data` caused it to not work!

Status: **Open for visibility**

Reviewers: @tedtate @kpeatt @Helen-Mobify 

## Changes
- fixed enabling/disabling inputs
- added checks to ensure these methods only run once if a pinny is open/lockup is locked.

## How to test-drive this PR
- checkout branch
- `grunt test`
- `grunt serve` and ensure that pinny is correctly enabling/disabling inputs on open/close

##TODO

- [ ] Write passing test for tab index storage on open
- [ ] Write passing test for tab index restoring on close

### CODE REVIEW

**Comment by scalvert** [comment]
@Helen-Mobify

**Comment by kpeatt** [comment]
We'll need to make this change to Pikabu as well.

**Comment by Helen-Mobify** [comment]
The document.activeElement can be undefined if there is an iframe in the pinny.

**Comment by scalvert** [comment]
OK I've done some rework with things like method names and also order of operations. I needed to tweak the order of operations of input disabling to ensure it was running at the correct time.

**Comment by Helen-Mobify** [comment]
:+1: looks good @scalvert

**Pull request merged**
